to give the branch name for removal

diff --git a/.github/workflows/removeSingleOldBranch.yml b/.github/workflows/removeSingleOldBranch.yml
--- a/.github/workflows/removeSingleOldBranch.yml
+++ b/.github/workflows/removeSingleOldBranch.yml
@@ -9,6 +9,12 @@ on:
         default: '10' # In days
         type: number
 
+      branch_name:
+        description: 'The name of the old branch to remove'
+        required: true
+        default: ""
+        type: string	
+
 jobs:
   RemoveSingleOldBranch:
     runs-on: ubuntu-latest
@@ -34,44 +40,53 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
         run: |
+          branch="${{ inputs.branch_name }}"
+	  if [ -z "$branch" ]; then
+            echo "Error: No branch name was provided."
+            exit 1
+          fi
+	  echo $branch
+
           #AGE_CUTOFF=360 # In days
           AGE_CUTOFF=${{ inputs.age_cutoff }} # In days
+          echo $AGE_CUTOFF
+
           #MAIN_BRANCH=master
           MAIN_BRANCH=main
-          echo $AGE_CUTOFF
+	  
           # Fetch all branches
           git branch -r | grep -v '\->' | sed 's/origin\///' > branches.txt
 
-          # Loop through branches
-          while read branch; do
-            # Skip main branch
-            if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
-              continue
-            fi
+          # Loop through branches-----------------------------------------------
+          #while read branch; do
+          # Skip main branch
+          if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
+            exit 1
+          fi
 
-            # Skip if open PR exists
-            open_prs=$(gh pr list --head "$branch" --json number --jq 'length')
-            if [ "$open_prs" -gt 0 ]; then
-              continue
-            fi
+          # Skip if open PR exists
+          open_prs=$(gh pr list --head "$branch" --json number --jq 'length')
+          if [ "$open_prs" -gt 0 ]; then
+            exit 1
+          fi
 
-            # Get last commit date
-            lastCommitDate=$(gh api repos/${{ github.repository }}/commits/$branch --jq '.commit.committer.date')
+          # Get last commit date
+          lastCommitDate=$(gh api repos/${{ github.repository }}/commits/$branch --jq '.commit.committer.date')
 
-            # Calculate branch age in days
-            branchAgeDays=$(( ($(date -u +%s) - $(date -u -d "$lastCommitDate" +%s)) / 86400 ))
+          # Calculate branch age in days
+          branchAgeDays=$(( ($(date -u +%s) - $(date -u -d "$lastCommitDate" +%s)) / 86400 ))
 
-            # Check whether the branch is old enough
-            if [ $branchAgeDays -ge $AGE_CUTOFF ]; then
-              # Get contributors to the branch
-              commitData=$(gh api "repos/${{ github.repository }}/compare/$MAIN_BRANCH...$branch")
-              contributors=$(printf '%s\n' "$commitData" | jq -r '.commits[] | select(.author.login != null) | "\(.commit.author.name) (@\(.author.login))"' | sort -u)
-              contributors=$(printf '%s\n' "$contributors" | paste -sd ', ' -)
+          # Check whether the branch is old enough
+          if [ $branchAgeDays -ge $AGE_CUTOFF ]; then
+            # Get contributors to the branch
+            commitData=$(gh api "repos/${{ github.repository }}/compare/$MAIN_BRANCH...$branch")
+            contributors=$(printf '%s\n' "$commitData" | jq -r '.commits[] | select(.author.login != null) | "\(.commit.author.name) (@\(.author.login))"' | sort -u)
+            contributors=$(printf '%s\n' "$contributors" | paste -sd ', ' -)
 
-              BLUE='\033[34m'
-              RED='\033[31m'
-              GREEN='\033[32m'
-              NC='\033[0m'
-              printf "BRANCH=${BLUE}%-20s${NC} AGE=${RED}%-20s${NC} OWNER=${GREEN}%s${NC}\n" "$branch" "${branchAgeDays} days old" "$contributors"
-            fi
-          done < branches.txt
+            BLUE='\033[34m'
+            RED='\033[31m'
+            GREEN='\033[32m'
+            NC='\033[0m'
+            printf "BRANCH=${BLUE}%-20s${NC} AGE=${RED}%-20s${NC} OWNER=${GREEN}%s${NC}\n" "$branch" "${branchAgeDays} days old" "$contributors"
+          fi
+          #done < branches.txt-----------------------------------------
